version: "3.9"
services:
  api:
    image: ${{ steps.login-ecr.outputs.registry }}/go-todo-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - jaeger

  web:
    image: ${{ steps.login-ecr.outputs.registry }}/go-todo-web:latest
    ports:
      - "80:80"
    depends_on:
      - api

  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"

volumes:
  mongo-data:
