name: Build, Push to ECR and Deploy to EC2

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # --- Build and Push API image ---
    - name: Build Docker image for API
      run: |
        docker build -t go-todo-api ./app
        docker tag go-todo-api:latest ${{ steps.login-ecr.outputs.registry }}/go-todo-api:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/go-todo-api:latest

    # --- Build and Push Web image ---
    - name: Build Docker image for Web
      run: |
        docker build -t go-todo-web ./web
        docker tag go-todo-web:latest ${{ steps.login-ecr.outputs.registry }}/go-todo-web:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/go-todo-web:latest

    - name: Create SSH key file
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > my-ec2-key
        chmod 600 my-ec2-key

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i my-ec2-key ec2-user@3.124.219.135 "mkdir -p /home/ec2-user/app"

        # копируем compose
        scp -o StrictHostKeyChecking=no -i my-ec2-key docker-compose.yml ec2-user@3.124.219.135:/home/ec2-user/app/docker-compose.yml

        # перезапускаем контейнеры
        ssh -o StrictHostKeyChecking=no -i my-ec2-key ec2-user@3.124.219.135 "
          cd /home/ec2-user/app &&
          docker-compose down || true &&
          docker-compose pull &&
          docker-compose up -d
        "
